### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by niklasmelin** [omnivector-solutions/jobbergate-cli#12]
Problem description:

While trying to list current applications, the authentication fails on line 45

main.py - JOBBERGATE_API_JWT_PATH.write_text(resp.json()['token']) KeyError: 'token'

The response from the server is:
Got response: {'email': ['This field is required.']}

Hence, I expect that the username should be replaced with email in the request to the api.
resp = requests.post(
        JOBBERGATE_API_OBTAIN_TOKEN_ENDPOINT,
        #data={"password": password, "username": username}
        data={"password": password, "email": username}
    )

**Comment by jamesbeedy** [comment]
Hey @niklasmelin good catch. I was making some last minute changes that use email instead of password for authentication [here](https://github.com/omnivector-solutions/jobbergate-cli/commit/45548fae6db918f0cc4dd5d5acd1f04e928a56dd#diff-fb16c38b022874f9858ef9cca054f4a0R41)

You will need to reinstall jobbergate-cli to pick up the changes.

**Comment by niklasmelin** [comment]
Ps. I Think my authentication doesnt work.

/niklas



Skickat från min Samsung Galaxy-smartphone.



-------- Originalmeddelande --------
Från: jamesbeedy <notifications@github.com>
Datum: 2020-08-25 16:03 (GMT+01:00)
Till: omnivector-solutions/jobbergate-cli <jobbergate-cli@noreply.github.com>
Kopia: Niklas Melin <niklasme@kth.se>, Mention <mention@noreply.github.com>
Ämne: Re: [omnivector-solutions/jobbergate-cli] Authentication problem (#12)


Hey @niklasmelin<https://github.com/niklasmelin> good catch. I was making some last minute changes that use email instead of password for authentication here<https://github.com/omnivector-solutions/jobbergate-cli/commit/45548fae6db918f0cc4dd5d5acd1f04e928a56dd#diff-fb16c38b022874f9858ef9cca054f4a0R41>

You will need to reinstall jobbergate-cli to pick up the changes.

-

**Comment by stephenkeefauver** [comment]
Niklas, are you still seeing this issue? If so, please connect with me on slack/email and we can sort it out. 

Thank you,

Stephen
