### ISSUE TITLE
Permission denied /tmp/jobbergate.py

### ISSUE THREAD

**Issue by niklasmelin** [omnivector-solutions/jobbergate-cli#15]
Procedure:
1. Reinstalled jobbergate in my venv using pip uninstall followed by the pip install git.....

2. Trying to create a job script with the command:
    jg create-job-script --name kabooom -i 34
3. Traceback: 
  File "/home/sssnks/test/nash/jobbergate-cli/lib64/python3.6/site-packages/jobbergate_cli/jobbergate_api_wrapper.py", line 290, in create_job_script
    application_file = open(MODULE_PATH, "w")
    PermissionError: [Errno 13] Permission denied: '/tmp/jobbergate.py'
4. Whats in /tmp
    (jobbergate-cli) /home/sssnks/test/nash> ll /tmp/ 
    -rw-r--r--. 1 nsxbxc scaniausers 4.1K Aug 27 13:22 jobbergate.py
   -rw-r--r--. 1 nsxbxc scaniausers  305 Aug 27 13:22 jobbergate.yaml

Is the problem connected to concurrent usage?

**Comment by jamesbeedy** [comment]
Yes it is. I thought we had patched this already. We can get a fix put the door momentarily. @niklasmelin thank you for reporting this.

**Comment by stephenkeefauver** [comment]
PR that resolves this by writing to ~/.jobbergate https://github.com/omnivector-solutions/jobbergate-cli/pull/16
